version: '3'

services:
  backend:
    build: ./backend
    image: backimage
    container_name: backcontainer
    ports:
      - "3000:80"
    environment:
      - NAME=World
    volumes:
      - ./backend:/app
    restart: unless-stopped
    
  frontend:
    build: ./frontend
    image: frontimage
    container_name: frontcontainer
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8000:80"
    depends_on:
      - backend